# k8s/manifests/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: vite-app-service
spec:
  type: NodePort
  selector:
    app: vite-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31000  # NodePort must be between 30000–32767
 
